---
# We want to use both instances for all upstream jobs including the `propose-downstream` one.
# For downstream, we need to pick just one instance (`stg` in our case)
# and redefine it for the `koji_build` and `bodhi_update` jobs.
packit_instances: ["prod", "stg"]
specfile_path: fedora/python-requre.spec
# https://packit.dev/docs/configuration/#top-level-keys
downstream_package_name: python-requre
upstream_project_url: https://github.com/packit/requre
issue_repository: https://github.com/packit/requre

# we are setting this so we can use packit from requre's dist-git
# packit can't know what's the upstream name when running from distgit
upstream_package_name: requre
# Use release description from GitHub when updating the
# changelog in Fedora.
copy_upstream_release_description: true
actions:
  # we need this b/c `git archive` doesn't put all the metadata in the tarball:
  #   LookupError: setuptools-scm was unable to detect version for '/builddir/build/BUILD/requre-0.11.1'.
  #   Make sure you're either building from a fully intact git repository or PyPI tarballs.
  create-archive:
    - python3 -m build --sdist --outdir ./fedora/
    - bash -c "ls -1t ./fedora/*.tar.gz | head -n 1"
  get-current-version:
    - hatch version

srpm_build_deps:
  - python3-build
  - hatch
  - python3-hatch-vcs

jobs:
  - job: sync_from_downstream
    trigger: commit
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9
  - job: copr_build
    trigger: commit
    branch: main
    project: packit-dev
    targets:
      - fedora-all
      - epel-9
    list_on_homepage: True
    preserve_project: True
  - job: copr_build
    trigger: release
    project: packit-releases
    targets:
      - fedora-all
      - epel-9
    list_on_homepage: True
    preserve_project: True

  # downstream automation:
  - job: koji_build
    trigger: commit
    packit_instances: ["stg"]
    dist_git_branches:
      - fedora-all
      - epel-9
  - job: bodhi_update
    trigger: commit
    packit_instances: ["stg"]
    dist_git_branches:
      - fedora-latest # branched version, rawhide updates are created automatically
      - fedora-stable
      - epel-9
