# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

FROM fedora:34

RUN dnf -y install \
    make \
    git \
    python3-pip \
    python3-pytest \
    python3-pytest-cov \
    # OGR is used in one of the e2e tests
    python3-ogr \
    && dnf clean all

WORKDIR /src
