---
- name: Check if we are not breaking ogr
  hosts: all
  tasks:
  - include_tasks: tasks/zuul-project-setup.yaml
  - include_tasks: tasks/generic-dnf-requirements.yaml
  - include_tasks: tasks/rpm-test-deps.yaml
  - include_tasks: tasks/ogr_reverse_dep_test.yaml
